from tkinter import *
from tkinter import ttk
class GUI_d_stats:
    """description of class"""
    def Assign(self, master, controller):
        self.stats_frame = ttk.Labelframe(master, text='Derived Stats')
        self.contr = controller

        self.lbl_lck = ttk.Label(self.stats_frame, text='Luck')
        self.lbl_hum = ttk.Label(self.stats_frame, text='Humanity')
        self.lbl_rec = ttk.Label(self.stats_frame, text='Recovery')
        self.lbl_end = ttk.Label(self.stats_frame, text='Endurance')
        self.lbl_run = ttk.Label(self.stats_frame, text='Run')
        self.lbl_sprint = ttk.Label(self.stats_frame, text='Sprint')
        self.lbl_swim = ttk.Label(self.stats_frame, text='Swim')
        self.lbl_leap = ttk.Label(self.stats_frame, text='Leap')
        self.lbl_hits = ttk.Label(self.stats_frame, text='Hits')
        self.lbl_stun = ttk.Label(self.stats_frame, text='Stun')
        self.lbl_sd = ttk.Label(self.stats_frame, text='Stun Defence')
        self.lbl_res = ttk.Label(self.stats_frame, text='Resistance')

        self.lck_var = StringVar()
        self.hum_var = StringVar()
        self.rec_var = StringVar()
        self.end_var = StringVar()
        self.run_var = StringVar()
        self.sprint_var = StringVar()
        self.swim_var = StringVar()
        self.leap_var = StringVar()
        self.hits_var = StringVar()
        self.stun_var = StringVar()
        self.sd_var = StringVar()
        self.res_var = StringVar()

        self.lbl_lck_val = ttk.Label(self.stats_frame, textvariable = self.lck_var)
        self.lbl_hum_val = ttk.Label(self.stats_frame, textvariable = self.hum_var)
        self.lbl_rec_val = ttk.Label(self.stats_frame, textvariable = self.rec_var)
        self.lbl_end_val = ttk.Label(self.stats_frame, textvariable = self.end_var)
        self.lbl_run_val = ttk.Label(self.stats_frame, textvariable = self.run_var)
        self.lbl_sprint_val = ttk.Label(self.stats_frame, textvariable = self.sprint_var)
        self.lbl_swim_val = ttk.Label(self.stats_frame, textvariable = self.swim_var)
        self.lbl_leap_val = ttk.Label(self.stats_frame, textvariable = self.leap_var)
        self.lbl_hits_val = ttk.Label(self.stats_frame, textvariable = self.hits_var)
        self.lbl_stun_val = ttk.Label(self.stats_frame, textvariable = self.stun_var)
        self.lbl_sd_val = ttk.Label(self.stats_frame, textvariable = self.sd_var)
        self.lbl_res_val = ttk.Label(self.stats_frame, textvariable = self.res_var)

        self.lbl_lck.grid(column=0, row = 0)
        self.lbl_hum.grid(column=0, row = 1)
        self.lbl_rec.grid(column=0, row = 2)
        self.lbl_end.grid(column=0, row = 3)
        self.lbl_run.grid(column=0, row = 4)
        self.lbl_sprint.grid(column=0, row = 5)
        self.lbl_swim.grid(column=0, row = 6)
        self.lbl_leap.grid(column=0, row = 7)
        self.lbl_hits.grid(column=0, row = 8)
        self.lbl_stun.grid(column=0, row = 9)
        self.lbl_sd.grid(column=0, row = 10)
        self.lbl_res.grid(column=0, row = 11)

        self.lbl_lck_val.grid(column = 1, row = 0)
        self.lbl_hum_val.grid(column = 1, row = 1)
        self.lbl_rec_val.grid(column = 1, row = 2)
        self.lbl_end_val.grid(column = 1, row = 3)
        self.lbl_run_val.grid(column = 1, row = 4)
        self.lbl_sprint_val.grid(column = 1, row = 5)
        self.lbl_swim_val.grid(column = 1, row = 6)
        self.lbl_leap_val.grid(column = 1, row = 7)
        self.lbl_hits_val.grid(column = 1, row = 8)
        self.lbl_stun_val.grid(column = 1, row = 9)
        self.lbl_sd_val.grid(column = 1, row = 10)
        self.lbl_res_val.grid(column = 1, row = 11)

        return self.stats_frame

    def update_stats(self):
        self.lck_var.set(self.contr.getChar_stat("Luck"))
        self.hum_var.set(self.contr.getChar_stat("Hum"))
        self.rec_var.set(self.contr.getChar_stat("Rec"))
        self.end_var.set(self.contr.getChar_stat("End"))
        self.run_var.set(self.contr.getChar_stat("Run"))
        self.sprint_var.set(self.contr.getChar_stat("Sprint"))
        self.swim_var.set(self.contr.getChar_stat("Swim"))
        self.leap_var.set(self.contr.getChar_stat("Leap"))
        self.hits_var.set(self.contr.getChar_stat("Hits"))
        self.stun_var.set(self.contr.getChar_stat("Stun"))
        self.sd_var.set(self.contr.getChar_stat("SD"))
        self.res_var.set(self.contr.getChar_stat("Res"))
        pass
