from tkinter import *
from tkinter import ttk

class GUI_wpn_info(object):
    """description of class"""
    def Assign(self, master, controller):
        self.contr = controller
        self.wpns_info_frame = ttk.Labelframe(master, text='Weapon details', width=100,  height=100)

        self.var_name = StringVar()
        self.var_type = StringVar()
        self.var_acc = StringVar()
        self.var_con = StringVar()
        self.var_ava = StringVar()
        self.var_dmg = StringVar()
        self.var_ammo = StringVar()
        self.var_shots = StringVar()
        self.var_rof = StringVar()
        self.var_rel = StringVar()
        self.var_rng = StringVar()
        self.var_cost = StringVar()
        self.var_source = StringVar()

        self.lbl_name = ttk.Label(self.wpns_info_frame, text='Name')
        self.lbl_type = ttk.Label(self.wpns_info_frame, text='Type')
        self.lbl_acc = ttk.Label(self.wpns_info_frame, text='Accuracy')
        self.lbl_con = ttk.Label(self.wpns_info_frame, text='Concealability')
        self.lbl_ava = ttk.Label(self.wpns_info_frame, text='Availability')
        self.lbl_dgm = ttk.Label(self.wpns_info_frame, text='Damage')
        self.lbl_ammo = ttk.Label(self.wpns_info_frame, text = 'Ammo')
        self.lbl_shots = ttk.Label(self.wpns_info_frame, text='Clipsize')
        self.lbl_rof = ttk.Label(self.wpns_info_frame, text='Rate of fire')
        self.lbl_rel = ttk.Label(self.wpns_info_frame, text='Reliability')
        self.lbl_rng = ttk.Label(self.wpns_info_frame, text='Range')
        self.lbl_cost = ttk.Label(self.wpns_info_frame, text='Cost')
        self.lbl_source = ttk.Label(self.wpns_info_frame, text='Source')

        self.lbl_name_val = ttk.Label(self.wpns_info_frame, textvariable = self.var_name,width = 40)
        self.lbl_type_val = ttk.Label(self.wpns_info_frame,  textvariable = self.var_type ,width = 40)
        self.lbl_acc_val = ttk.Label(self.wpns_info_frame, textvariable = self.var_acc ,width = 40)
        self.lbl_con_val = ttk.Label(self.wpns_info_frame, textvariable = self.var_con ,width = 40)
        self.lbl_ava_val = ttk.Label(self.wpns_info_frame, textvariable = self.var_ava ,width = 40)
        self.lbl_dgm_val = ttk.Label(self.wpns_info_frame, textvariable = self.var_dmg ,width = 40)
        self.lbl_ammo_val = ttk.Label(self.wpns_info_frame, textvariable = self.var_ammo ,width = 40)
        self.lbl_shots_val = ttk.Label(self.wpns_info_frame, textvariable = self.var_shots ,width = 40)
        self.lbl_rof_val = ttk.Label(self.wpns_info_frame, textvariable = self.var_rof ,width = 40)
        self.lbl_rel_val = ttk.Label(self.wpns_info_frame, textvariable = self.var_rel ,width = 40)
        self.lbl_rng_val = ttk.Label(self.wpns_info_frame, textvariable = self.var_rng ,width = 40)
        self.lbl_cost_val = ttk.Label(self.wpns_info_frame, textvariable = self.var_cost ,width = 40)
        self.lbl_source_val = ttk.Label(self.wpns_info_frame, textvariable = self.var_source ,width = 40)

        self.lbl_name.grid(column = 0, row = 0)
        self.lbl_type.grid(column = 0, row = 1)
        self.lbl_acc.grid(column = 0, row = 2)
        self.lbl_con.grid(column = 0, row = 3)
        self.lbl_ava.grid(column = 0, row = 4)
        self.lbl_dgm.grid(column = 0, row = 5)
        self.lbl_ammo.grid(column = 0, row = 6)
        self.lbl_shots.grid(column = 0, row = 7)
        self.lbl_rof.grid(column = 0, row = 8)
        self.lbl_rel.grid(column = 0, row = 9)
        self.lbl_rng.grid(column = 0, row = 10)
        self.lbl_cost.grid(column = 0, row = 11)
        
        self.lbl_name_val.grid(column = 1, row = 0)
        self.lbl_type_val.grid(column = 1, row = 1)
        self.lbl_acc_val.grid(column = 1, row = 2)
        self.lbl_con_val.grid(column = 1, row = 3)
        self.lbl_ava_val.grid(column = 1, row = 4)
        self.lbl_dgm_val.grid(column = 1, row = 5)
        self.lbl_ammo_val.grid(column = 1, row = 6)
        self.lbl_shots_val.grid(column = 1, row = 7)
        self.lbl_rof_val.grid(column = 1, row = 8)
        self.lbl_rel_val.grid(column = 1, row = 9)
        self.lbl_rng_val.grid(column = 1, row = 10)
        self.lbl_cost_val.grid(column = 1, row = 11)

        return self.wpns_info_frame

    def show_wpn_details(self, listbox):
        id = listbox.curselection()
        luku = int(id[0])
        wpn = self.contr.settings.all_weapons[listbox.get(luku)]
        wpn.test_me()
        min_dmg=wpn.getAttribute('min_dmg')
        max_dmg=wpn.getAttribute('max_dmg')
        self.var_name.set(wpn.getAttribute("Name"))
        self.var_type.set(wpn.getAttribute("type_text"))
        self.var_acc.set(wpn.getAttribute("WA"))
        self.var_con.set(wpn.getAttribute("con_text"))
        self.var_ava.set(wpn.getAttribute("ava_text"))
        self.var_dmg.set(str(min_dmg) + '-' + str(max_dmg))
        self.var_ammo.set(wpn.getAttribute("Ammo"))
        self.var_shots.set(wpn.getAttribute("Shots"))
        self.var_rof.set(wpn.getAttribute("ROF"))
        self.var_rel.set(wpn.getAttribute("rel_text"))
        self.var_rng.set(wpn.getAttribute("Range"))
        self.var_cost.set(wpn.getAttribute("Cost"))

